language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

install:
  - go mod download
  
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.13